---

- name: build docker image
  command: docker build ./ -t {{ item }} --no-cache
  args:
    chdir: "{{ working_directory }}/{{ app_name }}/docker-images/{{ item }}"
  with_items:
    - mahjong
    - mahjong-play-manager
