---

- name: build docker image
  command: docker build ./ -t {{ item }}
  args:
    chdir: "{{ working_directory }}/{{ app_name }}/docker-images/{{ item }}"
  with_items:
    - mahjong
    - mahjong-play-manager
    - matching-mysql
    - matching-python
