---

- name: docker-compose up
  command: /usr/local/bin/docker-compose up -d
  become_user: "{{ admin_user.name }}"
  environment:
    COMPOSE_FILE: "{{ 'docker-compose-' + '.yml:docker-compose-'.join(docker_container_names) + '.yml'}}"
  args:
    chdir: "{{ working_directory }}"

- name: Restart Nginx
  command: /usr/local/bin/docker-compose up -d --force-recreate
  become_user: "{{ admin_user.name }}"
  environment:
    COMPOSE_FILE: "{{ 'docker-compose-' + '.yml:docker-compose-'.join(docker_container_names) + '.yml'}}"
  args:
    chdir: "{{ working_directory }}"
  when: docker_compose_restart_nginx
