---

- name: create image directory
  local_action:
    module: file
    path: /usr/share/pinfu-challenge/images
    state: directory
  run_once: True

- name: copy external images
  copy:
    src: "{{ item }}"
    dest: "{{ ansistrano_deploy_to }}/current/mahjong-ui/images"
    owner: "{{ admin_user.name }}"
    mode: 644
  with_fileglob:
    - /usr/share/pinfu-challenge/images/*
