---

- name: Disable ssh login by root
  replace:
    path=/etc/ssh/sshd_config
    regexp="PermitRootLogin yes"
    replace="PermitRootLogin no"
  notify: restart sshd

- name: Copy a ssh config file
  template:
    src=config.j2
    dest="{{ working_directory }}/.ssh"
